DROP TABLE "SeminarParticipation" CASCADE CONSTRAINTS;

DROP TABLE "Seminar" CASCADE CONSTRAINTS;

DROP TABLE "Incentive" CASCADE CONSTRAINTS;

DROP TABLE "CustomerEvaluationType" CASCADE CONSTRAINTS;

DROP TABLE "CustomerEvaluation" CASCADE CONSTRAINTS;

DROP TABLE "PMEvaluationType" CASCADE CONSTRAINTS;

DROP TABLE "PMEvaluation" CASCADE CONSTRAINTS;

DROP TABLE "PeerEvaluationType" CASCADE CONSTRAINTS;

DROP TABLE "Contract" CASCADE CONSTRAINTS;

DROP TABLE "Salary" CASCADE CONSTRAINTS;

DROP TABLE "PeerEvaluation" CASCADE CONSTRAINTS;

DROP TABLE "Department" CASCADE CONSTRAINTS;

DROP TABLE "ParticipationProject" CASCADE CONSTRAINTS;

DROP TABLE "Project" CASCADE CONSTRAINTS;

DROP TABLE "Customer" CASCADE CONSTRAINTS;

DROP TABLE "Employee" CASCADE CONSTRAINTS;
